services:
  - type: pserv
    name: ziggy-db
    plan: free
    ipAllowList: []

  - type: web
    name: ziggy-api
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: EnableSwagger
        value: "true"
      - key: CORS__ALLOWED_ORIGINS
        value: https://ziggy-frontend.onrender.com
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: ziggy-db
          property: connectionString

  - type: web
    name: ziggy-frontend
    env: static
    rootDir: frontend
    buildCommand: |
      sed -i "s|https://yourdomain.com/api|$API_URL|g" src/environments/environment.prod.ts
      npm ci
      npm run build
    staticPublishPath: dist/food-delivery-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        value: https://ziggy-api.onrender.com/api
